name: Gradle Build

on:
    push:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        # container: wpilib/roborio-cross-ubuntu:2025-22.04
        - name: Checkout Thunder
          uses: actions/checkout@v3
        - name: Store Branch & Head
          run: |
                echo "GITHUB_THUNDER_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
                echo "GITHUB_THUNDER_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
        - name: Checkout and Initialize Thunder Test Repository
          uses: actions/checkout@v3
          with:
            repository: frc-862/thunder-actionstest
            ref: ''
            submodules: 'true'
        - name: Set Correct HEAD
          run: |
                cd src/main/java/frc/thunder
                git fetch
                git checkout $GITHUB_THUNDER_BRANCH
                git checkout $GITHUB_THUNDER_HEAD
        - name: Check Thunder Head
          run: git rev-parse HEAD
        # - name: Set Execution Permissions
        #   run: chmod +x ./gradlew
        # - name: Gradle Build Test
        #   run: ./gradlew build
