name: Gradle Build

on: [push, pull_request]

jobs:
    Build:
        runs-on: ubuntu-latest
        container: wpilib/roborio-cross-ubuntu:2025-22.04
        steps:
        - name: Checkout and Initialize Thunder Base Test
          uses: actions/checkout@v3
          with:
            repository: frc-862/thunder-actionstest
            ref: ''
            submodules: 'true'
        - name: Set Execution Permissions
          run: chmod +x ./gradlew && chmod +x ./set_submodule.sh
        - name: Find Commit
          run: ./set_submodule.sh
        - name: Init JDK
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
        - name: Gradle Build Test
          run: ./gradlew build
