name: Gradle Build

on: push:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        # container: wpilib/roborio-cross-ubuntu:2025-22.04
        - name: Checkout Thunder
          uses: actions/checkout@v3
        - name: Set Execution Permissions for Script
          run: chmod +x .github/store_head.sh
        - name: Store Head
          run: .github/store_head.sh
        - name: Checkout and Initialize Thunder Test Repository
          uses: actions/checkout@v3
          with:
            repository: frc-862/thunder-actionstest
            ref: ''
            submodules: 'true'
        - name: Initialize Thunder in Test Repository
          run: echo $THUNDER_HEAD
        # - name: Set Execution Permissions
        #   run: chmod +x ./gradlew
        # - name: Gradle Build Test
        #   run: ./gradlew build
